Advanced_expense_tracker/Exp_tracker_project/Exp_tracker_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exp_tracker_app.urls'))
]

Advanced_expense_tracker/Exp_tracker_project/exp_tracker_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "myapp"

urlpatterns = [
    path('', views.home, name='home'),
    path("edit/<int:id>/", views.edit, name="edit"),
    path("delete/<int:id>/", views.delete, name="delete")
]

Advanced_expense_tracker/Exp_tracker_project/exp_tracker_app/models.py
from django.db import models

# Create your models here.

class Expense(models.Model):

    def __str__(self):
        return self.name
    
    name = models.CharField(max_length=500)
    amount = models.IntegerField()
    category = models.CharField(max_length=500)
    date = models.DateField(auto_now=True) # this will set current date automatically

Advanced_expense_tracker/Exp_tracker_project/exp_tracker_app/forms.py
from django.forms import ModelForm
from .models import Expense

class ExpenseForm(ModelForm):
    class Meta:
        model = Expense
        fields = ("name", "amount", "category") # specify the field names which u want user to fill in the form.

Advanced_expense_tracker/Exp_tracker_project/exp_tracker_app/views.py
'''
we are using tailwind for this project and for this reason, we need nodejs in our machine because we need npm(node package manager) for tailwind.
1. install node js in system
2. npm init -y # this will create package.json inside app directory
3. npm install tailwindcss@2.2.16 # tailwind package will be added in package.json file as dependency
4. create src.css file inside static folder.
5. add below code in package.json file
"build": "tailwind build exp_tracker_app/static/tracker_app/src.css -o exp_tracker_app/static/tracker_app/styles.css"
6. in terminal run following command
npm run build # this will create new styles.css file with all styling codes.
'''

from django.shortcuts import render, redirect
from .forms import ExpenseForm
from .models import Expense
from django.db.models import Sum
import datetime

# Create your views here.

def home(request):
    if request.method == "POST":
        expense = ExpenseForm(request.POST)
        if expense.is_valid():
            expense.save()

    expenses = Expense.objects.all()
    total_expenses = expenses.aggregate(Sum('amount')) # to find total expense infrontend page instead of using javascript
    # print(total_expenses)

    # Logic to calculate last 365 days expense
    last_year = datetime.date.today() - datetime.timedelta(days=365) # substracting current datetime - datetime of 365 days before
    data = Expense.objects.filter(date__gt=last_year) # date__gt is nothing but date greater than last_year.
    yearly_sum = data.aggregate(Sum('amount')) # this will give yearly sum of expense.
    # print("yearly_sum: ", yearly_sum)

    # Logic to calculate last 30 days expense
    last_month = datetime.date.today() - datetime.timedelta(days=30)
    data = Expense.objects.filter(date__gt=last_month)
    monthly_sum = data.aggregate(Sum('amount'))

    # Logic to calculate last weekly expense
    last_week = datetime.date.today() - datetime.timedelta(days=7)
    data = Expense.objects.filter(date__gt=last_week)
    weekly_sum = data.aggregate(Sum('amount'))

    # Logic to calculate daily expense based on date
    daily_sums = Expense.objects.filter().values("date").order_by("date").annotate(sum=Sum('amount')) # this will filter on basis of date and order on basis of date
    # print("daily_sums: ", daily_sums)

    # Logic to calculate daily expense based on category
    categorical_sums = Expense.objects.filter().values("category").order_by("category").annotate(sum=Sum('amount')) # this will filter on basis of date and order on basis of date
    
    expense_form = ExpenseForm()
    return render(request, 'myapp/home.html', {"expense_form":expense_form, "expenses":expenses, "total_expenses":total_expenses, "yearly_sum":yearly_sum, "monthly_sum":monthly_sum, "weekly_sum":weekly_sum, "daily_sums":daily_sums, "categorical_sums":categorical_sums})

def edit(request, id):
    expense = Expense.objects.get(id=id)
    expense_form = ExpenseForm(instance=expense)
    if request.method == "POST":
        expense = Expense.objects.get(id=id)
        form = ExpenseForm(request.POST, instance=expense) # this will fetch form data in edit page
        if form.is_valid():
            form.save()
            return redirect("myapp:home")

    return render(request, "myapp/edit.html", {"expense_form":expense_form})



def delete(request, id):
    # expense = Expense.objects.get(id=id)
    # if request.method == "POST":
    #     expense.delete()
    #     return redirect("myapp:home")
    # return render(request, 'myapp/delete.html', {'expense':expense})

    # below code avoids delete.html and deletes that item once delete button is hit.

    if request.method == "POST" and 'delete' in request.POST: # this is because we have 2 post methods in home.html. so to avoid bugs, we added name=delete in delete button in home.html
        expense = Expense.objects.get(id=id)
        expense.delete()
    return redirect("myapp:home")

    

Advanced_expense_tracker/Exp_tracker_project/exp_tracker_app/templates/myapp/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "tracker_app/styles.css" %}">
    <link rel="stylesheet" href="{% static "tracker_app/style.css" %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="shadow-lg p-5">
        <div class="container flex flex-wrap justify-between items-center mx-auto">
            <a href="#" class="flex">
              <img class="w-20 h-20 mr-3" src="{% static 'tracker_app/images/wallet.png' %}" alt="">
              <span class="self-center text-xl font-semibold">Expense Tracker</span>
            </a>
        </div>
    </nav>
    {% block body %}
    {% endblock body %}
  </body>
</html>

Advanced_expense_tracker/Exp_tracker_project/exp_tracker_app/templates/myapp/delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are You sure you want to delete {{expense.name}}?</h2>
    <button type="submit">Confirm</button>
</form>

Advanced_expense_tracker/Exp_tracker_project/exp_tracker_app/templates/myapp/edit.html
{% extends "myapp/base.html" %}
{% block title %}Edit{% endblock title %}
{% block body %}

<form method="POST" class="shadow-lg m-10">
    {% csrf_token %}

    <div class="px-10 py-10 flex">

        <div class="mx-10">
            <div class="mb-5">
                <label class="font-semibold">Expense Name</label>
            </div>

            <div class="border p-1">
                {{expense_form.name}}
            </div>
        </div>

        <div class="mx-10">
            <div class="mb-5">
                <label class="font-semibold">Expense Amount</label>
            </div>

            <div class="border p-1">
                {{expense_form.amount}}
            </div>
        </div>

        <div class="mx-10">
            <div class="mb-5">
                <label class="font-semibold">Expense Category</label>
            </div>

            <div class="border p-1">
                {{expense_form.category}}
            </div>
        </div>

        <div class="mx-10 mt-10">
            <button class="bg-green-500 px-5 py-2 text-white font-bold" type="submit">Edit</button>
        </div>

    </div>

    <!-- {{expense_form}} -->   
</form>


{% endblock body %}

Advanced_expense_tracker/Exp_tracker_project/exp_tracker_app/templates/myapp/home.html
{% extends "myapp/base.html" %}
{% load static %}
{% load humanize %}
{% block title %}Home{% endblock title %}
{% block body %}

<div class="m-10 font-bold">Add Expense</div>


<form class="shadow-lg m-10 rounded-lg" method="POST">
    {% csrf_token %}

    <div class="form-container px-10 py-10 flex"> 
        <!-- flex will make columns side by side -->
        <div class="mx-10">

            <div class="mb-5">
                <label>Expense Name</label>
            </div>

            <div class="border">{{expense_form.name}}</div>

        </div>

        <div class="mx-10">

            <div class="mb-5">
                <label>Amount</label>
            </div>

            <div class="border">{{expense_form.amount}}</div>

        </div>

        <div class="mx-10">

            <div class="mb-5">
                <label>Category</label>
            </div>

            <div class="border">{{expense_form.category}}</div>

        </div>

        <div class="mx-10 mt-10">
            <button class="bg-green-500 px-5 py-2 rounded-lg text-white font-bold">Add</button>
        </div>

    </div>
</form>

<div class="m-10 font-bold">Expenses</div>

<div class="shadow-lg m-10 rounded-lg">
    
    <div class="expense-header flex flex-wrap space-x-40 px-20 py-5">
        <span>Name</span>
        <span>Amount</span>
        <span>Category</span>
        <span>Date</span>
        <span>Edit</span>
        <span>Delete</span>
    </div>
    <hr class="m-10">

    {% for expense in expenses %}
    <div class="expense-row flex-wrap px-20 py-5">
        <span class="font-bold">{{expense.name}}</span>
        <span class="font-bold">Rs.{{expense.amount|intcomma}}/-</span>
        <span class="font-bold">{{expense.category}}</span>
        <span class="font-bold">{{expense.date}}</span>
        <!-- <span class="font-bold"><a href="{% url "myapp:edit" expense.id %}">Edit</a></span> -->
        <span class="pl-24"><a href="{% url 'myapp:edit' expense.id %}"><img class="h-7 w-7" src="{% static 'tracker_app/images/edit.png' %}" alt=""></a></span>
        {% comment %} <span class="font-bold"><a href="{% url 'myapp:delete' expense.id %}">Delete</a></span> {% endcomment %}
        <span class="pl-22">
            <form method="POST" action="{% url 'myapp:delete' expense.id %}">
                {% csrf_token %}
                <button type="submit" name="delete"><img class="h-7 w-7" src="{% static 'tracker_app/images/delete.png' %}" alt=""></button>
            </form>
        </span>
    </div>
    {% endfor %}
    <!-- Displaying total -->
    <div class="px-20 pl-20 py-5">
        <span class="font-bold text-green-500">
            Total: Rs. {{total_expenses.amount__sum|intcomma}}/-
        </span>
    </div>

    <!-- Displaying total -->
</div>

<!-- {% for expense in expenses %}
{{expense.name}}
{{expense.amount}}
{{expense.category}}
{{expense.date}}
<br>
{% endfor %} -->


{% comment %} Below codes are used to display weekly, monthly, yearly expenses {% endcomment %}

<div class="flex">

    <div class="w-1/3 shadow-lg ml-10 rounded-lg">
        <h1 class="ml-10 font-bold text-grey-500">Last 365 days</h1>
        <h1 class="ml-10 my-5 text-2xl text-green-500 font-bold">
            Rs.{{yearly_sum.amount__sum|intcomma}}/-
        </h1>
    </div>

    <div class="w-1/3 shadow-lg ml-10 rounded-lg">
        <h1 class="ml-10 font-bold text-grey-500">Last 30 days</h1>
        <h1 class="ml-10 my-5 text-2xl text-green-500 font-bold">
            Rs.{{monthly_sum.amount__sum|intcomma}}/-
        </h1>
    </div>

    <div class="w-1/3 shadow-lg ml-10 rounded-lg">
        <h1 class="ml-10 font-bold text-grey-500">Last week</h1>
        <h1 class="ml-10 my-5 text-2xl text-green-500 font-bold">
            Rs.{{weekly_sum.amount__sum|intcomma}}/-
        </h1>
    </div>

</div>

{% comment %} Below codes are used to display daily expenses based on date{% endcomment %}

<div class="flex">
     <div class="w-1/2 shadow-lg m-10">

        <div class="flex flex-wrap space-x-40 font-bold px-20 py-5">
            <span>Past 30 days sum expenses</span>
        </div>
        <hr>

        <div id="30-day-table" class="">
            {% for daily_sum in daily_sums %}

                <div class="flex flex-wrap px-20 py-5">
                    <span>
                        {{daily_sum.date}}
                    </span>
                </div>

                <div class="flex flex-wrap px-20 py-5">
                    <span class="text-green-500">
                        Rs.{{daily_sum.sum}}/-
                    </span>
                </div>

            {% endfor %}
        </div>

     </div>


    {% comment %} Below codes are used to display daily expenses based on category {% endcomment %}

    <div class="w-1/2 shadow-lg m-10">

        <div class="flex flex-wrap space-x-40 font-bold px-20 py-5">
            <span>Past 30 days categorical expenses</span>
        </div>
        <hr>

        <div id="cat-sum-table" class="">
            {% for categorical_sum in categorical_sums %}

                <div class="flex flex-wrap px-20 py-5">
                    <span>
                        {{categorical_sum.category}}
                    </span>
                </div>

                <div class="flex flex-wrap px-20 py-5">
                    <span class="text-green-500">
                        Rs.{{categorical_sum.sum}}/-
                    </span>
                </div>

            {% endfor %}
        </div>

    </div>
</div>

<div class="flex">
    <div class="w-1/2 shadow-lg ml-10">
        <h1 class="m-10">Expense spread across category</h1>
        <canvas id="myChart" class="m-10"></canvas>
    </div>

    <div class="w-1/2 shadow-lg ml-10">
        <h1 class="m-10">Daily Expense Sum</h1>
        <canvas id="myChart1" class="m-10"></canvas>
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.2/dist/chart.min.js"></script>

<script>
    // below codes are used to fetch category values

    const category = []
    const category_sums = []

    const dates = []
    const sums = []

    const catSumDiv = document.getElementById("cat-sum-table").getElementsByTagName("div") // in cat-sum-table id, we have no of div elements. so we are saying getElementsByTagName("div")
    
    for(i=0; i<catSumDiv.length; i++){
        if (i%2==1){ // if i value is odd, fetch value for expense
            category_sums.push(catSumDiv[i].innerText.replace("Rs.","").replace("/-",""))
        }else{ // if i value is even, fetch category values like personal, electronics, cosmetics etc
            category.push(catSumDiv[i].innerText)
        }
    }
    // console.log(category_sums)

    const dailySumDiv = document.getElementById("30-day-table").getElementsByTagName("div") // in cat-sum-table id, we have no of div elements. so we are saying getElementsByTagName("div")
    
    for(i=0; i<dailySumDiv.length; i++){
        if (i%2==1){ // if i value is odd, fetch value for date
            sums.push(dailySumDiv[i].innerText.replace("Rs.","").replace("/-",""))
        }else{ // if i value is even, fetch category values like personal, electronics, cosmetics etc
            dates.push(dailySumDiv[i].innerText)
        }
    }


    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: category,
        datasets: [{
            label: '# of Votes',
            data: category_sums,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});

console.log(dates)
console.log(sums)

var ctx1 = document.getElementById('myChart1').getContext('2d');
    var myChart1 = new Chart(ctx1, {
    type: 'line',
    data: {
        labels: dates,
        datasets: [{
            label: 'Sum of daily expenses',
            data: sums,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>

{% endblock body %}