Time_chat_application/Time_chat/Time_chat/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rooms/', include('time_app.urls'))
]

Time_chat_application/Time_chat/time_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "time"

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.chatroom, name='chatroom'),
]

Time_chat_application/Time_chat/time_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ChatRoom(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)


class ChatMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    message_content = models.TextField()
    date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('date',) # this will retrieve messages from db based on date order.

Time_chat_application/Time_chat/time_app/views.py
from django.shortcuts import render
from .models import ChatRoom, ChatMessage
# Create your views here.

def home(request):
    chatrooms = ChatRoom.objects.all()
    return render(request, 'app/home.html', {"chatrooms":chatrooms})

def chatroom(request, slug):
    chatroom = ChatRoom.objects.get(slug=slug)
    messages = ChatMessage.objects.filter(room=chatroom)[0:30]
    return render(request, 'app/room.html', {"chatroom":chatroom, "messages":messages})

Time_chat_application/Time_chat/time_app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="shadow-lg px-3 py-2.5">
        <div class="container flex flex-wrap justify-between mx-auto">
            <a class="flex items-center" href="">
                <img class="h-16 mr-3" src="https://cdn2.iconfinder.com/data/icons/whcompare-isometric-web-hosting-servers/50/email-laptop-256.png" alt="">
                <span class="self-center text-4xl font-semibold">Chats App</span>
            </a>

            <div class="w-full block w-auto">
                <ul class="flex flex-row p-4 mt-4 border rounded-lg border-gray-100 bg-blue-50">
                    <li>
                        <a class="block py-2 pl-3 pr-4 rounded bg-blue-700 text-white" href="">Rooms</a>
                    </li>

                    <li>
                        <a class="block py-2 pl-3 pr-4 rounded " href="">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock body %}


  </body>
</html>

Time_chat_application/Time_chat/time_app/templates/app/home.html
{% extends "app/base.html" %}
{% block body %}
<h1 class="font-bold m-10">List of rooms</h1>
{% for chatroom in chatrooms %}
  <div class="shadow-lg p-10 m-10 bg-blue-700 text-white rounded-lg">
        
    <a href="{% url 'time:chatroom' chatroom.slug %}">{{chatroom.name}}</a>
    
  </div>
  {% endfor %}

{% endblock body %}

Time_chat_application/Time_chat/time_app/templates/app/room.html
{% extends "app/base.html" %}
{% block body %}

<div class="m-10 font-bold">
    {{chatroom.name}}
</div>

<!-- {{request.user.username}}  -->
<!-- above code will fetch user name who has logged in. -->
<div class="message-container m-10 overflow-auto h-[700px]" id="message-container">
    <div id="chat-messages">
        <!-- above code is used to display user message on frontend html page. we make use of id='chat-messages' in JS codes below -->
        
            {% for message in messages %}
            <div class="message shadow-lg p-3 m-3 rounded-lg w-1/2 bg-blue-300">
                <div class="text-sm text-gray-500">
                    {{message.user.username}}
                </div>
                    {{message.message_content}}
                <div class="text-sm text-gray-500">
                    {{message.date}}
                </div>
                
            </div>
            {% endfor %}
        </div> 
</div>

<div class="form-container fixed inset-x-0 bottom-0 bg-blue-900 p-4">
    <form method="POST">
        {% csrf_token %}
        <input class="rounded-md px-2" id="message-input" type="text" name="message" placeholder="Enter message">
        <button class="text-white ml-5" id="send-button" type="submit">Send</button>
    </form>
</div>


{{chatroom.slug|json_script:"json-chatroomname"}}
{{request.user.username|json_script:"json-username"}} 
<!-- above code will fetch user name who has logged in. -->

<script>
    const chatRoomName = JSON.parse(document.getElementById('json-chatroomname').textContent);
    // above code will fetch slug from particular chatroom(chatroom from views.py) from django or html to javascript.

    const username = JSON.parse(document.getElementById('json-username').textContent);
    // above code will fetch username from particular chatroom(chatroom from views.py) from django or html to javascript.

    const chatSocket = new WebSocket(
        'ws://' // similar to http://
        + window.location.host // this line will fetch/give url i.e 127.0.0.1:8000
        + '/ws/' // we are adding ws/ because in routing.py, we have specified ws/ in path
        + chatRoomName 
        + '/' // because we need / at end 
    )
    chatSocket.onmessage = function(e){
        // console.log("This is a message")
        const data = JSON.parse(e.data)
        if (data.message){
            console.log("Received message to client: ", data.message) // This will print message in console.
            let html = '<div class="message shadow-lg p-3 m-3 rounded-lg w-1/2 bg-blue-300">' + '<div class="text-sm text-gray-500">' + data.username + " </div> " + data.message + '<div class="text-sm text-gray-500">' + 'Now' +  '</div>'// This will print message in frontend html page.
            document.getElementById("chat-messages").innerHTML += html
            scroll()
        }else{
            alert("The message was empty")
        }
    }
    chatSocket.onclose = function(e){
        console.log("Socket closed")
    }

    document.getElementById("send-button").onclick = function(e){
        e.preventDefault() // this will avoid refreshing of page when send button is clicked after entering message and send message to socket.

        const messageInput = document.getElementById("message-input") // this will get access for message input field
        const message = messageInput.value // this will get message entered by user
        console.log(message)

        chatSocket.send(JSON.stringify({ // this will send user input message to socket in consumers.py from front end to backend
            'message':message,
            'username':username,
            'room':chatRoomName, 

        }))

        messageInput.value = "" // this line will set message field to empty once message is sent by user. i.e message field will be empty after message is submitted by user.


    }

    function scroll(){
        const mcontainer = document.getElementById('message-container')
        mcontainer.scrollTop = mcontainer.scrollHeight
    }
    scroll()
</script>

{% endblock body %}